# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/lars/Documents/Github/DSP/cfg/clocks.xdc

# XDC: /home/lars/Documents/Github/DSP/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_pll_0_2/system_pll_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pll_0_2 || ORIG_REF_NAME==system_pll_0_2} -quiet] -quiet

# IP: bd/system/ip/system_ps_0_2/system_ps_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps_0_2 || ORIG_REF_NAME==system_ps_0_2} -quiet] -quiet

# IP: bd/system/ip/system_rst_0_2/system_rst_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_0_2 || ORIG_REF_NAME==system_rst_0_2} -quiet] -quiet

# IP: bd/system/ip/system_axis_ram_reader_0_0/system_axis_ram_reader_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_ram_reader_0_0 || ORIG_REF_NAME==system_axis_ram_reader_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_1_0/system_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_1_0 || ORIG_REF_NAME==system_xlconstant_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# XDC: bd/system/ip/system_pll_0_2/system_pll_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_2 || ORIG_REF_NAME==system_pll_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_pll_0_2/system_pll_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_2 || ORIG_REF_NAME==system_pll_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_pll_0_2/system_pll_0_2_ooc.xdc

# XDC: bd/system/ip/system_ps_0_2/system_ps_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ps_0_2 || ORIG_REF_NAME==system_ps_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_0_2/system_rst_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_2 || ORIG_REF_NAME==system_rst_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_0_2/system_rst_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_2 || ORIG_REF_NAME==system_rst_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_0_2/system_rst_0_2_ooc.xdc

# XDC: bd/system/system_ooc.xdc
