# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ywang/Code/red-pitaya-notes/cfg/ports.xdc

# XDC: /home/ywang/Code/red-pitaya-notes/cfg/clocks.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_Waveform_Offset_Addr_1/system_Waveform_Offset_Addr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_Waveform_Offset_Addr_1 || ORIG_REF_NAME==system_Waveform_Offset_Addr_1} -quiet] -quiet

# IP: bd/system/ip/system_ps_0_2/system_ps_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps_0_2 || ORIG_REF_NAME==system_ps_0_2} -quiet] -quiet

# IP: bd/system/ip/system_writer_0_2/system_writer_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_writer_0_2 || ORIG_REF_NAME==system_writer_0_2} -quiet] -quiet

# IP: bd/system/ip/system_writer_0_3/system_writer_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_writer_0_3 || ORIG_REF_NAME==system_writer_0_3} -quiet] -quiet

# IP: bd/system/ip/system_Waveform_Offset_Addr_2/system_Waveform_Offset_Addr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_Waveform_Offset_Addr_2 || ORIG_REF_NAME==system_Waveform_Offset_Addr_2} -quiet] -quiet

# IP: bd/system/ip/system_adc_0_0/system_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_adc_0_0 || ORIG_REF_NAME==system_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_c_counter_binary_0_0/system_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_c_counter_binary_0_0 || ORIG_REF_NAME==system_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cfg_0_0/system_cfg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_cfg_0_0 || ORIG_REF_NAME==system_cfg_0_0} -quiet] -quiet

# IP: bd/system/ip/system_concat_0_0/system_concat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_concat_0_0 || ORIG_REF_NAME==system_concat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_const_0_0/system_const_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_const_0_0 || ORIG_REF_NAME==system_const_0_0} -quiet] -quiet

# IP: bd/system/ip/system_not_0_0/system_not_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_not_0_0 || ORIG_REF_NAME==system_not_0_0} -quiet] -quiet

# IP: bd/system/ip/system_pll_0_0/system_pll_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] -quiet

# IP: bd/system/ip/system_port_slicer_4_0/system_port_slicer_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_port_slicer_4_0 || ORIG_REF_NAME==system_port_slicer_4_0} -quiet] -quiet

# IP: bd/system/ip/system_ps_0_axi_periph_0/system_ps_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps_0_axi_periph_0 || ORIG_REF_NAME==system_ps_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_pulse_gen_0_0/system_pulse_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pulse_gen_0_0 || ORIG_REF_NAME==system_pulse_gen_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_0_0/system_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] -quiet

# IP: bd/system/ip/system_sig_exp_decay_0_0/system_sig_exp_decay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sig_exp_decay_0_0 || ORIG_REF_NAME==system_sig_exp_decay_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_0/system_slice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_slice_2_0 || ORIG_REF_NAME==system_slice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_3_0/system_slice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_slice_3_0 || ORIG_REF_NAME==system_slice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_2_0/system_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_2_0 || ORIG_REF_NAME==system_xlconcat_2_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_poly_0_0/system_fir_poly_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_poly_0_0 || ORIG_REF_NAME==system_fir_poly_0_0} -quiet] -quiet

# IP: bd/system/ip/system_port_slicer_0_0/system_port_slicer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_port_slicer_0_0 || ORIG_REF_NAME==system_port_slicer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_port_slicer_0_1/system_port_slicer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_port_slicer_0_1 || ORIG_REF_NAME==system_port_slicer_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axis_broadcaster_0_0/system_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_broadcaster_0_0 || ORIG_REF_NAME==system_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_combiner_0_0/system_axis_combiner_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_combiner_0_0 || ORIG_REF_NAME==system_axis_combiner_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/ip/system_ps_0_2/system_ps_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ps_0_2 || ORIG_REF_NAME==system_ps_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_c_counter_binary_0_0/system_c_counter_binary_0_0_ooc.xdc

# XDC: bd/system/ip/system_pll_0_0/system_pll_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_pll_0_0/system_pll_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_pll_0_0/system_pll_0_0_ooc.xdc

# XDC: bd/system/ip/system_rst_0_0/system_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_0_0/system_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_0_0/system_rst_0_0_ooc.xdc

# XDC: bd/system/ip/system_axis_broadcaster_0_0/system_axis_broadcaster_0_0_ooc.xdc

# XDC: bd/system/ip/system_axis_combiner_0_0/system_axis_combiner_0_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
