# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/cfg/clocks.xdc

# XDC: imports/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_Waveform_Offset_Addr_1/system_Waveform_Offset_Addr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_Waveform_Offset_Addr_1 || ORIG_REF_NAME==system_Waveform_Offset_Addr_1} -quiet] -quiet

# IP: bd/system/ip/system_cfg_0_2/system_cfg_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_cfg_0_2 || ORIG_REF_NAME==system_cfg_0_2} -quiet] -quiet

# IP: bd/system/ip/system_const_0_2/system_const_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_const_0_2 || ORIG_REF_NAME==system_const_0_2} -quiet] -quiet

# IP: bd/system/ip/system_pll_0_2/system_pll_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pll_0_2 || ORIG_REF_NAME==system_pll_0_2} -quiet] -quiet

# IP: bd/system/ip/system_ps_0_2/system_ps_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps_0_2 || ORIG_REF_NAME==system_ps_0_2} -quiet] -quiet

# IP: bd/system/ip/system_ps_0_axi_periph_2/system_ps_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps_0_axi_periph_2 || ORIG_REF_NAME==system_ps_0_axi_periph_2} -quiet] -quiet

# IP: bd/system/ip/system_rst_0_2/system_rst_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_0_2 || ORIG_REF_NAME==system_rst_0_2} -quiet] -quiet

# IP: bd/system/ip/system_slice_3_2/system_slice_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_slice_3_2 || ORIG_REF_NAME==system_slice_3_2} -quiet] -quiet

# IP: bd/system/ip/system_writer_0_2/system_writer_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_writer_0_2 || ORIG_REF_NAME==system_writer_0_2} -quiet] -quiet

# IP: bd/system/ip/system_axis_constant_0_0/system_axis_constant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_constant_0_0 || ORIG_REF_NAME==system_axis_constant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/ip/system_pll_0_2/system_pll_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_2 || ORIG_REF_NAME==system_pll_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_pll_0_2/system_pll_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_2 || ORIG_REF_NAME==system_pll_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_pll_0_2/system_pll_0_2_ooc.xdc

# XDC: bd/system/ip/system_ps_0_2/system_ps_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ps_0_2 || ORIG_REF_NAME==system_ps_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_0_2/system_rst_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_2 || ORIG_REF_NAME==system_rst_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_0_2/system_rst_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_2 || ORIG_REF_NAME==system_rst_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_0_2/system_rst_0_2_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
